# —————————
# 基础设置
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
ipv6: true
mode: Rule
allow-lan: true
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
global-ua: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36
unified-delay: true
tcp-concurrent: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#面板默认 Meta 可选 Yacd / Zash 重启模块即可加载
external-ui: /data/adb/box_bll/panel/Zash/ # 主推zash
secret: ""
# —————————
# ==== Tips

# 1. 修改配置文件保存时，建议重启服务/重载配置.
# 2. 如遇代理组图标无法显示，确保Tun保持开启状态下，您可先尝试 关闭/开启网络
# 3. 启动Webapk可检查是否能访问上 raw.githubusercontent.com 如无提示即通过
# —————————


# 健康检查
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
  header:
      User-Agent:
      - "mihomo/1.19.3"
      - "clash.meta"
# —————————

# 订阅地址相关
A: &A
  filter: "^(?!.*(套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|失联|余额)).*$"
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

All: &All
  type: url-test
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

proxy-providers: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↓
  1.主要地址:
    <<: *p
    override:
      additional-prefix: "Main："
    path: ./proxies/1.主要地址.yaml
    url: "引入您的Clash订阅链接地址"

  2.备用地址:
    <<: *p
    override:
      additional-prefix: "Minor："
    path: ./proxies/2.备用地址.yaml
    url: "引入您的Clash订阅链接地址"

  3.额外地址:
    <<: *p
    override:
      additional-prefix: "Additi："
    path: ./proxies/3.额外地址.yaml
    url: "引入您的Clash订阅链接地址"

# —————————

# 节点记忆
profile: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↑
  store-selected: true
  store-fake-ip: true
# —————————

# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
# —————————

# 网卡模块
# ==== Tips
# 1. Tp无法劫持发往局域网的请求，也会导致WebRTC地址泄露DNS会有劫持抢答风险
tun:
  enable: true #true 开 #false 关 # 防止地址泄露此项必须开启
  device: meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - fc00::/7
    - fe80::/10
  exclude-package: # 游戏卡顿可添加包名 仅Android
    #- com.tencent.tmgp.sgame
    # _____________________# 三星专供 ↓ 范围
#    - com.samsung.android.messaging
#    - com.samsung.android.app.telephonyui
#    - com.samsung.android.dialer
#    - com.samsung.android.incallui
#    - com.samsung.android.smartcallprovider
#    - com.samsung.android.intellivoiceservice
#    - com.android.settings
#    - com.qti.qcc
#    - com.sec.epdg
#    - com.sec.imsservice # 三星专供 ↑ 范围
    # 非三星用户不必理会，三星用户可自行取消注释
    
# —————————

hosts:
  raw.githubusercontent.com:
    - 185.199.109.133
    - 185.199.108.133
    - 185.199.110.133
    - 185.199.111.133
    - 2606:50c0:8000::154
    - 2606:50c0:8001::154
    - 2606:50c0:8002::154
    - 2606:50c0:8003::154

# DNS模块
# 解析不懂别瞎改养蛊 已最优解，你再怎么折腾也是没啥卵用
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "GeoSite:CN,private"
    - "localhost.ptlogin2.qq.com"
  proxy-server-nameserver:
    - https://doh.pub/dns-query#🌎 全球直连
    - https://dns.alidns.com/dns-query#🌎 全球直连&h3=true
  nameserver-policy:
    "GeoSite:CN":
       - https://doh.pub/dns-query#🌎 全球直连
       - https://dns.alidns.com/dns-query#🌎 全球直连&h3=true
  nameserver:
    - https://dns.google/dns-query#DNS解析&h3=true
    - https://cloudflare-dns.com/dns-query#DNS解析&h3=true
# —————————

proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: ⛔️ 拒绝连接, type: reject}
  - {name: 🌐 DNS_Hijack, type: dns}

proxy_groups: &proxy_groups
    type: select
    proxies:
      - 总模式
      - ⛔️ 拒绝连接
      - 延迟最低
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 其它地区
      - 🌎 全球直连
    <<: *A
# —————————
proxy-groups:
  - name: 总模式
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/All.svg"
    type: select
    proxies:
      - 延迟最低
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 其它地区
      - 🌎 全球直连
# —————————

  - name: Telegram
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Telegram.svg"
    <<: *proxy_groups
    
  - name: Apple
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Apple.svg"
    <<: *proxy_groups
    
  - name: Microsoft
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Microsoft.svg"
    <<: *proxy_groups

  - name: OpenAI
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/OpenAI.svg"
    <<: *proxy_groups

  - name: Discord
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Discord.svg"
    <<: *proxy_groups

  - name: TikTok
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/TikTok.svg"
    <<: *proxy_groups

  - name: YouTube
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/YouTube.svg"
    <<: *proxy_groups

  - name: Netflix
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Netflix.svg"
    <<: *proxy_groups

  - name: Facebook
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Facebook.svg"
    <<: *proxy_groups

  - name: Google
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Google.svg"
    <<: *proxy_groups

  - name: GoogleFCM
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/GoogleFCM.svg"
    <<: *proxy_groups

  - name: GitHub
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/GitHub.svg"
    <<: *proxy_groups

  - name: Twitter(X)
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Twitter.svg"
    <<: *proxy_groups

  - name: DNS解析
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/DNS.svg"
    <<: *proxy_groups

  - name: 漏网之鱼
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/HBASE-copy.svg"
    <<: *proxy_groups

  - name: 广告拦截
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/No-ads-all.svg"
    type: select
    proxies:
      - ⛔️ 拒绝连接
      - 🌎 全球直连
      - REJECT-DROP
      - PASS #匹配规则

  - name: 延迟最低
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: url-test
    <<: *A

  - name: 故障转移
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: fallback
    <<: *A

  - name: 负载均衡
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: load-balance
    strategy: round-robin
    <<: *A

  - name: 台湾节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/CN.svg"
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan)).*$"
    <<: *All

  - name: 香港节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/HK.svg"
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    <<: *All

  - name: 日本节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/JP.svg"
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)).*$"
    <<: *All

  - name: 美国节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/US.svg"
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$"
    <<: *All

  - name: 狮城节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Singapore.svg"
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"
    <<: *All

  - name: 其它地区
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Globe.svg"
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网)).*$"
    <<: *All
# —————————

rules:
  - DST-PORT,53,🌐 DNS_Hijack
  - GeoSite,category-ads-all,广告拦截
  - GeoSite,Twitter,Twitter(X)
  - GeoSite,GitHub,GitHub
  - GeoSite,Discord,Discord
  - GeoSite,TikTok,TikTok
  - GeoSite,YouTube,YouTube
  - GeoSite,Netflix,Netflix
  - GeoSite,Facebook,Facebook
  - GeoSite,OpenAI,OpenAI
  - GeoSite,GoogleFCM,GoogleFCM
  - GeoSite,Google,Google
  - GeoSite,Apple,Apple
  - GeoSite,Microsoft,Microsoft
  - GeoSite,Telegram,Telegram
  - GeoSite,CN,🌎 全球直连
  - GeoSite,private,🌎 全球直连,no-resolve
  - GeoIP,CN,🌎 全球直连
  - GeoIP,private,🌎 全球直连,no-resolve
  - MATCH,漏网之鱼
# —————————
